[tool.poetry]
name = "terminal"
version = "0.0.1dev1"
description = "Common terminal maintained by y0urself"
authors = ["Jaspar Löchte <info@greenbone.net>"]
license = "GPL-3.0-or-later"
readme = "README.md"

classifiers=[
  # Full list: https://pypi.org/pypi?%3Aaction=list_classifiers
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  # pylint: disable=line-too-long
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

packages = [
  { include = "terminal"},
  { include = "tests", format = "sdist" },
  { include = "poetry.lock", format = "sdist" },
  { include = "poetry.toml", format = "sdist" },
]
include = [
  "pontos/updateheader/templates/"
]

[tool.poetry.dependencies]
python = "^3.7"
colorful = "^0.5.4"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
autohooks = "^21.7.0"
autohooks-plugin-pylint = "^21.6.0"
autohooks-plugin-black = {version = "^21.7.1", python = "^3.6"}
black = {version = "21.7b0", python = "^3.6"}
rope = "^0.20.1"
coverage = "^6.0"

[tool.black]
line-length = 80
target-version = ['py35', 'py36', 'py37', 'py38']
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.venv
  | \.circleci
  | \.github
  | \.vscode
  | _build
  | build
  | dist
  | docs
)/
'''

[tool.autohooks]
pre-commit = ['autohooks.plugins.black', 'autohooks.plugins.pylint']
mode = "poetry"

[tool.pontos.version]
version-module-file = "terminal/__version__.py"

[tool.poetry.scripts]
terminal-example = 'terminal.example:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
